[package]
name = "crabgo-credential"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crabgo"
description = "A library to assist writing Crabgo credential helpers."

[dependencies]
