[package]
name = "xtask-unpublished"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
crabgo.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
