[package]
name = "semver-check"
version = "0.0.0"
authors = ["Eric Huss"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/crabgo/reference/manifest.html

[dependencies]
tempfile.workspace = true
