'\" t
.TH "CRABGO\-HELP" "1"
.nh
.ad l
.ss \n[.ss] 0
.SH "NAME"
crabgo\-help \[em] Get help for a Crabgo command
.SH "SYNOPSIS"
\fBcrabgo help\fR [\fIsubcommand\fR]
.SH "DESCRIPTION"
Prints a help message for the given command.
.SH "EXAMPLES"
.sp
.RS 4
\h'-04' 1.\h'+01'Get help for a command:
.sp
.RS 4
.nf
crabgo help build
.fi
.RE
.RE
.sp
.RS 4
\h'-04' 2.\h'+01'Help is also available with the \fB\-\-help\fR flag:
.sp
.RS 4
.nf
crabgo build \-\-help
.fi
.RE
.RE
.SH "SEE ALSO"
\fBcrabgo\fR(1)
